language: go

go:
    - 1.6

env:
    matrix:
        # - TMP_GIMME_OS=darwin TMP_GIMME_ARCH=386 TMP_GIMME_TYPE=binary
        # - TMP_GIMME_OS=darwin TMP_GIMME_ARCH=amd64 TMP_GIMME_TYPE=binary
        # - TMP_GIMME_OS=linux TMP_GIMME_ARCH=386 TMP_GIMME_TYPE=binary
        - TMP_GIMME_OS=linux TMP_GIMME_ARCH=amd64 TMP_GIMME_TYPE=binary
        # - TMP_GIMME_OS=windows TMP_GIMME_ARCH=386 TMP_GIMME_TYPE=binary
        # - TMP_GIMME_OS=windows TMP_GIMME_ARCH=amd64 TMP_GIMME_TYPE=binary
    global:
        - secure: "FqOqp2bWrcQ2vTVqHAj5RhvMra7sxWU4TEoTq2CWz0s20+vL/B36fOPL69kIZ9sHfcxlW76HH2hdhsHokC82rnXOLfsM6m00A8nYqhOQleuS1lGTwMqXhC019+sX7RiuX4OghvZ4Jh3QMJ3nZLBJGy6YQ0F3LH6AZVbjHoBLUpvTeNuvVI06JRqm1oUssNwjeL5r6tV0OREIslXl6Ess/RR1Zx0+aJ+Hn6XrOCO+cqs0uHCWNKlmyFl9VTjMB2WwIWsNH6YCPHtBFSfUsbyj1tDnwLXlraSLCY4kA6y/atW693Lrg18CvnaTw2sEbCKVE3K/tFd2S4CXQ1hSymQSkYGiBjrylfOCH5o//lfZptEmwjCht7e30cqcOvbUmYUEcQ29BJEWvEj0OXebFPmfxxRllBdWQppRvRiaOQJgUIKiRsQhia9NzEhXecgXp5HKqJf5CYaxatRD6WAixUj5DcIfSsxpFgJgI3DqkuQdiK4e4frWJSPNMKyFwGgrcRoMoLAdqopgx1zr2ehVhw1VxOcTZYVauJClU0chBnKnK7+TVbRk7/VknegV1+rFAFtP1GgChB2Fjs+zTjibWO5qkkU+QNj6NlPsu4V71xOnx3XbcTq9RUKY4/ymqL9W81GHKZ7smI+q47/qDrihlX1dmfqGYnMn77YcAIuWvNQ4KWo="

# workaround for travis-ci/gimme#25 to pick up latest version of gimme and run again
before_install:
  - export GIMME_OS=${TMP_GIMME_OS}
  - export GIMME_ARCH=${TMP_GIMME_ARCH}
  - export GIMME_TYPE=${TMP_GIMME_TYPE}
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
  - curl -o gimme -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
  - chmod u+x gimme
  - unset GOROOT GOTOOLDIR GIMME_NO_ENV_ALIAS
  - ./gimme -l
  - ./gimme 1.6
  - ./gimme -l
  - ./gimme --force 1.6
  - ./gimme -l
  - source ~/.gimme/envs/go1.6.env
  - go version
  - go env

script:
  - go install -v ./...
  - chmod ugo+x travis_run_go_test.sh
  - ./travis_run_go_test.sh

after_success:
  - cd $GOPATH/bin/
  - export CURRENT_ENV_DIR=${GIMME_OS}_${GIMME_ARCH}
  - export PCKG_FILE=${CURRENT_ENV_DIR}.zip
  - mkdir -p $CURRENT_ENV_DIR/sanity_check
  - cp -f $GOPATH/bin/* $CURRENT_ENV_DIR/
  - mv $CURRENT_ENV_DIR/dbcheck $CURRENT_ENV_DIR/sanity_check/
  # Make sure that out sanity checks are also bundled with the executable
  - cp -R $TRAVIS_BUILD_DIR/dbcheck/tests $CURRENT_ENV_DIR/sanity_check/
  - zip -r $PCKG_FILE $CURRENT_ENV_DIR

before_deploy:
  # It can cause the deploy to fail, if you are not in the build dir at deploy time.
  - cd $TRAVIS_BUILD_DIR

deploy:
  provider: releases
  user: palette-robot
  password:
    secure: N3uCGfcjH3x4vgntcPVQ+e46lXxL3wu3I5ZbxrI6POJxIeBr1xyDtz5pfmHDTgSgCuJ6x7sTmq9DDBacG8cB9KI/HAPKKd6j2kI9PbYu0QDj90OaAcy6WQsvKRE2Qn+MQEFjmNL1uiBQS6S/Sk35vaQtcs/RMKPin0Q57tlLEFC+yjFJ2eOXRKVgceS5Fug4OXec3cUkxMAla88kks0/6gin5GAz97xXAFcB1VK7I336wiOklQTMqAhaG7YSAGQwDSvhgY9zP/Pfi18OxYh1dPTSVW9lbDgfzMsZDzKD7fSGm8isTYMVQguGnqSHeF3DZQsOgHHh28pv7AKRVPM1sANMNoABi9I8pZ5F0MDcq0OmI4UP0Ai8f37mmV1FGrbUMtXlyOkGgVTk5mRJRJqIYomHrOgXGXuYR1W1JWgLJG5JLJSOgek/PT0gce1haGbg0cGUEKPTPrWn8n0jHolA8MZ7uWGZjpYKhudGf1/t5egOAeIPu4w+0UdHwb4bEK9r6TNmjNv8Oke7imxoZ0R5nA0M3qB5yZyysZnLgDHM0GV1CiPWEwL/+nGf3ybHjhogMsAkgEDGynDy1qfRTi7Cg4rtDbsKplnJZOO/a1yauug7U+R7FBl8ku+xtoHMigo3sB1239xGZDsz4n5j4yNfrqugMEdtX0QggNzt1CqOVOU=
  file:
  - ${GOPATH}/bin/${GIMME_OS}_${GIMME_ARCH}.zip
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
