language: go

go:
  - 1.6
env:
  matrix:
    - TMP_GOOS=linux TMP_GOARCH=386
    - TMP_GOOS=linux TMP_GOARCH=amd64
    - TMP_GOOS=windows TMP_GOARCH=amd64
    - TMP_GOOS=windows TMP_GOARCH=386
    - TMP_GOOS=darwin TMP_GOARCH=amd64
    - TMP_GOOS=darwin TMP_GOARCH=386
  global:
    - secure: "lOgnr2pC7J+uoXqU5GITWRlPCheVFgjUdB0Q0kcYsEqilMMDjDdxJBymxr/1xewfgJZoW2NVGJScm7VOZJ1r4fhPvSf3ltjp/n7EK9eDo4bHYxD7WYNF4nG3wF4pvYhACxO/tEMrozXwCwJ9wfdSd2PiFLjutlKchI6AHaB2mDTdcoJDlclCfbpfL50l9lHfVnlolabmqvNnrSiTpyM7kCuNBS7mbxofxy6mPciBM0fX9eKYpE9vZJIVnwiJOumcRIglZtTyhtyloiFFl1e7dhew9sYdqq2Fck1XRzjWXpj98YUlabomZG7AIQe/q8o9UevNbyV0TlFxH3ScZLs8iCMbURilufSIPmK6eyJbrJq+SsNDYrm/1FdHqlip4JQ84G+mczW5koOmew3JHTY8V6C+N0gqnEtZpZ3xUybWBOWfQu5bNud6/Uya/lOsp8AX0mbNBNluTZ3yDcLN/o01HVoCqMcpFgud/clJ4iLmlusIs9DTdz3gCanr27rTS6ET6r/IIcbkNg/MafVcPXDvVLhAZ5+ZuXH1M8SaXo4bdJeIV1cNJB4RcSivByml1U6xtyKbLQUY+quFWwPA/KsHLaxshqclYkGrHTTmM2YFmd8DQ4uft9EGvIAxJ/VOnscRtk1ksdv+Xil2eZxEvYLZl3WFjBhMVd8O0sL4o5w5M4c="
    - PACKAGE_VERSION=2.0.$TRAVIS_BUILD_NUMBER
    - OWNER=palette-software
    - PACKAGE=insight-tester

before_install:
  - export GOOS=${TMP_GOOS}
  - export GOARCH=${TMP_GOARCH}
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc

script:
  - go install -v ./...
  - chmod ugo+x travis_run_go_test.sh
  - ./travis_run_go_test.sh

after_success:
  - cd $GOPATH/bin/
  - export CURRENT_ENV_DIR=${GOOS}_${GOARCH}
  - export PCKG_FILE=${CURRENT_ENV_DIR}.zip
  - mkdir -p $CURRENT_ENV_DIR/sanity_check
  - cp -f $GOPATH/bin/* $CURRENT_ENV_DIR/
  - mv $CURRENT_ENV_DIR/dbcheck $CURRENT_ENV_DIR/sanity_check/
  # Make sure that out sanity checks are also bundled with the executable
  - cp -R $TRAVIS_BUILD_DIR/dbcheck/tests $CURRENT_ENV_DIR/sanity_check/
  - zip -r $PCKG_FILE $CURRENT_ENV_DIR

before_deploy:
  # It can cause the deploy to fail, if you are not in the build dir at deploy time.
  - cd $TRAVIS_BUILD_DIR

deploy:
  skip_cleanup: true
  provider: script
  # Only deploy from the master branch (and if we don't have a tag specified, because they are auto-committed)
  script: $TRAVIS_BUILD_DIR/release-to-github.sh
  on:
    # It should be master!!!
    branch: sanity_check_ok_logs
    tags: false

notifications:
  email: false
