language: go
sudo: required

go:
  - 1.6
env:
  matrix:
    - TMP_GOOS=linux TMP_GOARCH=386
    - TMP_GOOS=linux TMP_GOARCH=amd64
    - TMP_GOOS=windows TMP_GOARCH=amd64
    - TMP_GOOS=windows TMP_GOARCH=386
    - TMP_GOOS=darwin TMP_GOARCH=amd64
    - TMP_GOOS=darwin TMP_GOARCH=386
  global:
    #  GITHUB_TOKEN
    - secure: "FOq3cQWUoOJBBxVhTxZ9CME2/faJId/Gb9MMAkAtZ3ZZNJ0g1dM7oYazD+WlVUnG4aKO45hLz3IYqozhziUf07H6JVCkdeRhsL06GgfwAhWYV3QsvXdsFkBGOO7xxFgLZCaGqeYjiOswpvLSJAYKkp3OWzzGFKqB+OHm0mYs43dj28vtUset6vpADH7DNwTsLiO4gPzxOSeGBGhV+QHEv63H5xZGx6VxiXzUn/lxYiuIhYHwzy//p0Pg+4t0XMrNn5Fb63tI7489IQIM7waNlL2UiPAR7AhNiQPhWPEhdNieLvHHhgRLLpxNXHOAtT3ZwhtiV7uURrbTKVnBM9JVPuj+8hXNU3I2NPYMOtJ9O01EkHloEFOFLgZf0ZOYhvxNbVOMC2qqqqxhM8EOGC+4jVM+CQnUhquNnKmO7GSN2wFvG7KJ3TYhgpyhGtUCAnF+wVFeSoh4w/8a27KIShvugLejiNxYET0UtrQsKaKcYxKdn6iYTuSNhqhdgT4WL3JztSn0AJjMybSHS840yPQOOulJMnVi0DHqii1x8jE87V1/dq29HVe/4bNx3YSO5xVLQKPjBv7qPumhoq57tjYKyqEdHpr+fhC7ha5woo/ROBua/32qKHUa1UanfPiO0C12vJ5RSYzayCr1eIK9aqsiW55A9VeUs8kF3yBgK2buz/w="
    - VERSION=2.0.$TRAVIS_BUILD_NUMBER
    - PRODUCT_VERSION=v${VERSION}
    - OWNER=palette-software
    - PACKAGE=insight-tester
    # GP_PALETTE_PASSWORD
    - secure: "LdWnOffjxBKJoF5kEJz/HDj9hKCGJxrG5PyfA0XFNOOJtrshT842C1e+4AT+fDf8KFzZvNcQJi+mo11z1Pk1IhJI3w/j9vRhaub8Ts34Z1w9Ds+pr+wShUdh+A3krFQdfWncFmapD097Ztmp+6/vYji4k2ljczFqVfLDHp/4PC1uDGcKf0ubfRrRy1fvNIk23YjtZzLqp3goFIVr19JTDdk8NOXvuU+Pu+Jjhw9waUnmyE2KzZN40NenVX5omwA+y9SqNhXUwHFu9y9R9eMyHj06puEZG6RLaKvR85LK5D03K4EqsQ6X3MsG2yeL5hGAj90G52bPoyG1h2bHlkCUHgLZwgJZs0RInuEJm15Ccpv1MKCboMTYzjB6donCyvzItOgRumTrKreP6J4uBKdtx9qPHkxxcKCho1A39f4yFFOy+rH5D9Ji7R7OOZcUA8svCy/CgC3fULFiEclY0Qz4E7Vah2yenT3hppKLmJJslD4wsh0lpVdmrzbF8u/Gqp8SOSV1orw1mgV1MyhP12acDFrfJD4e2GsaXDEudcnjPK5s3eumoLoeRedRL0YYXObKXPsu5qcHA8BDJXA7unVGREZqiF41t93llP+pQhQDKqpa4mKIPGXJLOgWAGVNjfkdJ5z9hazml9vGjw5Rpisr6j4gtEVJkyHUOe3jYtOTmr4="
    - DEPLOY_HOST=rpm.palette-software.com
    - DEPLOY_PATH=/var/palette-rpm-repo
    - DEPLOY_USER=palette-rpm
    # DEPLOY_PASS
    - secure: "E06wrnHb8pB5jQs7d0IYpYd5J1FAqVAXW24f9Gcs6IkNdoRQEM321f11V7h0tdPPIstidP1LPn70ezH0DnOzlnDJ0DiBLwRdjvLv2WmFGohTFDV9ymygisCnux/M1GQyZQlt/jptDnO+Ebifz9MaVbeYtPo/wHI3rqHb6uKKJDHkan6jOaT76BSM89iRTa/x6AEw0WdSO+3TodikqCDati60RIQl14kCvWAsWQtItmBiLBqWFe+t1v7FbAa4DaR40Hemisj68l67lSfO+0tJI7VSUqp/5ojh/BjLWH9movnBtR9FGh9qyNigbZ1v0YuRTKfaWO6hTgL+DCdfOIpqDQf50LGAPZB1uHoq26wztvEhORAP/aMMv99jE4cbQOVg4hhGNw7zXwWXiMUQEVapbZlZdWVvrgDLTNbJJKK4cJtaBZXuMayiyotWRdePltL+j1yvtag/XuM8FSCDRd4ZdcEe/oNucfMRoK44XF4tE7pSwLmq2YwgAC5LtPs42H/gHgK2nqIY4yUp3hReuF7hejam1HK0DPkKvzGG7ZImrGgHcZYH11K4iUaDELy4xz04281fLNmlUbifJtWmQD6A891yCMEB7ALINdREzM6KOrIyIXaO3SS5K1qR0DR9s/p+6XPdEjER4NqQFmtj4rWE7pyCQk91uq1tCRvJNqMhnnY="

# install the RPM package
addons:
  apt:
    packages:
      - rpm
      # To deploy the rpms, we need to ssh into places, and we dont want to store keys for now
      - sshpass

before_install:
  - export GOOS=${TMP_GOOS}
  - export GOARCH=${TMP_GOARCH}
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc

script:
  - go install -v ./...
  - chmod ugo+x travis_run_go_test.sh
  - ./travis_run_go_test.sh

after_success:
  - cd $GOPATH/bin/
  - export PCKG_DIR=`pwd`
  - export CURRENT_ENV_DIR=${GOOS}_${GOARCH}
  - export PCKG_FILE=${CURRENT_ENV_DIR}.zip
  - mkdir -p $CURRENT_ENV_DIR/sanity_check
  - cp -f $GOPATH/bin/* $CURRENT_ENV_DIR/
  - mv $CURRENT_ENV_DIR/dbcheck $CURRENT_ENV_DIR/sanity_check/
  - mv $CURRENT_ENV_DIR/csv_forker $CURRENT_ENV_DIR/sanity_check/
  # Make sure that our sanity checks are also bundled with the executable
  - cp -R $TRAVIS_BUILD_DIR/dbcheck/tests $CURRENT_ENV_DIR/sanity_check/
  - zip -r $PCKG_FILE $CURRENT_ENV_DIR

  # build the rpm
  - cd ${TRAVIS_BUILD_DIR}/dbcheck
  - if [ "${CURRENT_ENV_DIR}" == "linux_amd64" ]; then rpmbuild -bb --buildroot $(pwd) --define "version $VERSION" --define "buildrelease 1" --define 'source_dir $TRAVIS_BUILD_DIR' --define "_rpmdir $(pwd)/_build" palette-insight-sanity-check.spec; fi

before_deploy:
  # It can cause the deploy to fail, if you are not in the build dir at deploy time.
  - cd $TRAVIS_BUILD_DIR

deploy:
  skip_cleanup: true
  provider: script
  # Only deploy from the master branch (and if we don't have a tag specified, because they are auto-committed)
  script: ./deploy.sh
  on:
    branch: master
    tags: false

notifications:
  email: false
