language: go
sudo: required

go:
  - 1.6
env:
  matrix:
    - TMP_GOOS=linux TMP_GOARCH=386
    - TMP_GOOS=linux TMP_GOARCH=amd64
    - TMP_GOOS=windows TMP_GOARCH=amd64
    - TMP_GOOS=windows TMP_GOARCH=386
    - TMP_GOOS=darwin TMP_GOARCH=amd64
    - TMP_GOOS=darwin TMP_GOARCH=386
  global:
    - secure: "omw0SJff3lD9tIM1LSeWoDotXVyMbF2mNi6ZoIQa+dMSvHY+aQ7C9vLcCz9xaBHcwhwfIO4Fely7+vPw+rBpcYQyGPp1PxDLBsHuEHLN1QR5hzAZ84aVQTg8rWhTEikvdonBWJw8388g+ZPUIhlUy31QCNQXBEWCl3G2yljsfaxde2Ju0gZx+gcmtSyQZeNTGGap7GZwZ+MLfseZp45TlR9OgyqjMLNFXVdM8bQ7g6DHCVgQduxDCachF0wmZ38O8T5M3qZf+5I0Zq39tuVyT6R3FHsyrDcK4GqLNqabTU0u9QwN77P/JUGEtgw4sZIaSBfQ35E4vVT3RhA85eaSLhf8AOdwAv9svWk+xsYlDlLj800Lk4YCaBYOmnAurwLS4i1csyoaAlnLzE4BDfNVkb2GMUekroK+hxVgsVMI8Gjz3RkkPxWhuN977eT8LL4gFqjRKxwEBC8zVTZYgGm4utLJOwYtXFq9zjeZndOtH+MUPGCeWxdHytMAGiJA1Jm3UJPYS6vdJnGZy2z4lKB2UTZBzFRaXqZv2HZ4ejvYJFVG1eMdp+S+r+gh6HWb4zTNz5tyalMUFXYLgARX116SFV6KClIXXX0E02B4h7/5bQpxE9d2Ts68rhrDukCrr5pqPQwLciQKmcN+vT/ALuoWdWQVH5B6zyqCQk5LVcCD8so="
    - PRODUCT_VERSION=v1.0.$TRAVIS_BUILD_NUMBER
    - OWNER=palette-software
    - PACKAGE=insight-tester

before_install:
  - export GOOS=${TMP_GOOS}
  - export GOARCH=${TMP_GOARCH}
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc

script:
  - go install -v ./...
  - chmod ugo+x travis_run_go_test.sh
  - ./travis_run_go_test.sh

after_success:
  - cd $GOPATH/bin/
  - export PCKG_DIR=`pwd`
  - export CURRENT_ENV_DIR=${GOOS}_${GOARCH}
  - export PCKG_FILE=${CURRENT_ENV_DIR}.zip
  - mkdir -p $CURRENT_ENV_DIR/sanity_check
  - cp -f $GOPATH/bin/* $CURRENT_ENV_DIR/
  - mv $CURRENT_ENV_DIR/dbcheck $CURRENT_ENV_DIR/sanity_check/
  - mv $CURRENT_ENV_DIR/csv_forker $CURRENT_ENV_DIR/sanity_check/
  # Make sure that out sanity checks are also bundled with the executable
  - cp -R $TRAVIS_BUILD_DIR/dbcheck/tests $CURRENT_ENV_DIR/sanity_check/
  - zip -r $PCKG_FILE $CURRENT_ENV_DIR

before_deploy:
  # It can cause the deploy to fail, if you are not in the build dir at deploy time.
  - cd $TRAVIS_BUILD_DIR

deploy:
  skip_cleanup: true
  provider: script
  # Only deploy from the master branch (and if we don't have a tag specified, because they are auto-committed)
  script: $TRAVIS_BUILD_DIR/release-to-github.sh
  on:
    branch: master
    tags: false

notifications:
  email: false
