language: go

go:
  - 1.6
env:
  matrix:
    - TMP_GOOS=linux TMP_GOARCH=386
    - TMP_GOOS=linux TMP_GOARCH=amd64
    - TMP_GOOS=windows TMP_GOARCH=amd64
    - TMP_GOOS=windows TMP_GOARCH=386
    - TMP_GOOS=darwin TMP_GOARCH=amd64
    - TMP_GOOS=darwin TMP_GOARCH=386
  global:
    - secure: "FqOqp2bWrcQ2vTVqHAj5RhvMra7sxWU4TEoTq2CWz0s20+vL/B36fOPL69kIZ9sHfcxlW76HH2hdhsHokC82rnXOLfsM6m00A8nYqhOQleuS1lGTwMqXhC019+sX7RiuX4OghvZ4Jh3QMJ3nZLBJGy6YQ0F3LH6AZVbjHoBLUpvTeNuvVI06JRqm1oUssNwjeL5r6tV0OREIslXl6Ess/RR1Zx0+aJ+Hn6XrOCO+cqs0uHCWNKlmyFl9VTjMB2WwIWsNH6YCPHtBFSfUsbyj1tDnwLXlraSLCY4kA6y/atW693Lrg18CvnaTw2sEbCKVE3K/tFd2S4CXQ1hSymQSkYGiBjrylfOCH5o//lfZptEmwjCht7e30cqcOvbUmYUEcQ29BJEWvEj0OXebFPmfxxRllBdWQppRvRiaOQJgUIKiRsQhia9NzEhXecgXp5HKqJf5CYaxatRD6WAixUj5DcIfSsxpFgJgI3DqkuQdiK4e4frWJSPNMKyFwGgrcRoMoLAdqopgx1zr2ehVhw1VxOcTZYVauJClU0chBnKnK7+TVbRk7/VknegV1+rFAFtP1GgChB2Fjs+zTjibWO5qkkU+QNj6NlPsu4V71xOnx3XbcTq9RUKY4/ymqL9W81GHKZ7smI+q47/qDrihlX1dmfqGYnMn77YcAIuWvNQ4KWo="

before_install:
  - export GOOS=${TMP_GOOS}
  - export GOARCH=${TMP_GOARCH}
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc

script:
  - go install -v ./...
  - chmod ugo+x travis_run_go_test.sh
  - ./travis_run_go_test.sh

after_success:
  - cd $GOPATH/bin/
  - export CURRENT_ENV_DIR=${GOOS}_${GOARCH}
  - export PCKG_FILE=${CURRENT_ENV_DIR}.zip
  - mkdir -p $CURRENT_ENV_DIR/sanity_check
  - cp -f $GOPATH/bin/* $CURRENT_ENV_DIR/
  - mv $CURRENT_ENV_DIR/dbcheck $CURRENT_ENV_DIR/sanity_check/
  # Make sure that out sanity checks are also bundled with the executable
  - cp -R $TRAVIS_BUILD_DIR/dbcheck/tests $CURRENT_ENV_DIR/sanity_check/
  - zip -r $PCKG_FILE $CURRENT_ENV_DIR

before_deploy:
  # It can cause the deploy to fail, if you are not in the build dir at deploy time.
  - cd $TRAVIS_BUILD_DIR

deploy:
  provider: releases
  api_key:
    secure: "eEABG6TD6/oaM6pd64wDmNYWkwdGg2SNtJqgPNW4chO1gUZqdtVKzsv5LGfYFNpMPcuypsnL/2+6FACCfpg8JzvkTdNEGaYUMNyXecJAU39n90gbxlvke/LoFtn0z4LNTl17VaJebu7X7elSo0Wiu6RKahR8UB47hIAEkyVmjX9sPOFdWuhZ9j5Hq9rk+2bYVmnNQuZcruRaK8MYqRpXWwiNUQZK+mBPvn7/muQWlZT93Vrwg059m99iN1LZIkVvRqoFCDJrBwBUl7Bhv51aAkk/ozXR/TX2/mSwEcbA36RFRC+hhVJ45J4JeRN+vctkpiTqJuDyYhw5tvXAIZ9cmPEso60nv0/8XnRM/FJh0OoPHGXLAmLWuTixjjBVjbSbBnuYOFXxav5pkhk9auqiUV2cywvc9ZZh3+2RPYRqP7KH2nKzj1SK0CnfBiN8iwOu2WbCDswKrLb6Z4uEUyo69U5V+IYovKTiweJneDUZmbndcGxmm2sr3l/1+jVmPf0abjMQrzdxNqXvIiu7+sy8HG9EADIpOhONcY3oqU/9QxZOnlJh88Pzl7J0Mri+Sx4KJPRh2rE80jlHyE1z76UYQgoqj49V39x9N+QGlWnI4HavkkWysLJXbly4LJDvii9hHECq981gzxMbCNkTWuZo2X96c1JaY93IihcleZB9gwU="
  file:
  - ${GOPATH}/bin/${GOOS}_${GOARCH}.zip
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
