language: go

go:
    - 1.5

env:
  matrix:
  # - GIMME_OS=darwin GIMME_ARCH=386
  # - GIMME_OS=darwin GIMME_ARCH=amd64
  # - GIMME_OS=linux GIMME_ARCH=386
  - GIMME_OS=linux GIMME_ARCH=amd64
  # - GIMME_OS=windows GIMME_ARCH=386
  # - GIMME_OS=windows GIMME_ARCH=amd64
  global:
  - secure: FqOqp2bWrcQ2vTVqHAj5RhvMra7sxWU4TEoTq2CWz0s20+vL/B36fOPL69kIZ9sHfcxlW76HH2hdhsHokC82rnXOLfsM6m00A8nYqhOQleuS1lGTwMqXhC019+sX7RiuX4OghvZ4Jh3QMJ3nZLBJGy6YQ0F3LH6AZVbjHoBLUpvTeNuvVI06JRqm1oUssNwjeL5r6tV0OREIslXl6Ess/RR1Zx0+aJ+Hn6XrOCO+cqs0uHCWNKlmyFl9VTjMB2WwIWsNH6YCPHtBFSfUsbyj1tDnwLXlraSLCY4kA6y/atW693Lrg18CvnaTw2sEbCKVE3K/tFd2S4CXQ1hSymQSkYGiBjrylfOCH5o//lfZptEmwjCht7e30cqcOvbUmYUEcQ29BJEWvEj0OXebFPmfxxRllBdWQppRvRiaOQJgUIKiRsQhia9NzEhXecgXp5HKqJf5CYaxatRD6WAixUj5DcIfSsxpFgJgI3DqkuQdiK4e4frWJSPNMKyFwGgrcRoMoLAdqopgx1zr2ehVhw1VxOcTZYVauJClU0chBnKnK7+TVbRk7/VknegV1+rFAFtP1GgChB2Fjs+zTjibWO5qkkU+QNj6NlPsu4V71xOnx3XbcTq9RUKY4/ymqL9W81GHKZ7smI+q47/qDrihlX1dmfqGYnMn77YcAIuWvNQ4KWo=
before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
  - curl -o gimme -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
  - chmod u+x gimme
  - unset GOROOT GOTOOLDIR GIMME_NO_ENV_ALIAS
  - eval "$(./gimme 1.5)"
  - go version
  - go env

script:
  - go install -v ./...
  - chmod ugo+x travis_run_go_test.sh
  - ./travis_run_go_test.sh

after_success:
  - cd $GOPATH/bin/
  - export CURRENT_ENV_DIR=${GIMME_OS}_${GIMME_ARCH}
  - export PCKG_FILE=${CURRENT_ENV_DIR}.zip
  - mkdir -p $CURRENT_ENV_DIR/sanity_check
  - cp -f $GOPATH/bin/* $CURRENT_ENV_DIR/
  - mv $CURRENT_ENV_DIR/dbcheck $CURRENT_ENV_DIR/sanity_check/
  # Make sure that our sanity checks are also bundled with the executable
  - cp -R $TRAVIS_BUILD_DIR/dbcheck/tests $CURRENT_ENV_DIR/sanity_check/
  - zip -r $PCKG_FILE $CURRENT_ENV_DIR

before_deploy:
  # It can cause the deploy to fail, if you are not in the build dir at deploy time.
  - cd $TRAVIS_BUILD_DIR

deploy:
  provider: releases
  user: palette-robot
  file: ${GOPATH}/bin/${GIMME_OS}_${GIMME_ARCH}.zip
  skip_cleanup: true
  on:
    tags: true
    branch: fix-deploy
  password:
    secure: SOMsTPNM91hPvewobWV6A/mjVcyZtswnZbcfMGx4l66vzmHDhRTp8DwAI3LT/SBhBfv+YIOWlk9gscyhX+sxWSbyYGDHL3fgTdR1OwyyAIa/Qbqmr6RwxRBa/a/PWyLqe39Fxtdcq3NScUonBTuCP4zLtNYQ0hCRi12eIV6HsVsjybkVeIg8vzSwtlRop/1Z0+40mwu0oJU6Vn/XX8E/gNSAaBxK0ugOm3n7JgrF7sBbnddqT3RCLwDQT5uW1le5fTaS9xd/ZCVOBv4Clt9MiZDc7POXgDVmpkUMhlxn4UB/H1WsQXQzzBQVmP48X9yL54DaFdlyS14qRct4WgGAJYMCEutf9wYALp9UfmGzZ4VJnoucs3JDeBxpxg3FsdpcKfHDTeNx8oqOoMyNJh0EX0aUBnP+viGOxPQJCs8lhK3atY14RvNBMYSzYvptAwuR8U2YHDNAgwZhZbk2h481APtldjjCDUVpg9+nm31e1j9yUD1RwMQBOT2BKhag8uCmEFfiy8xzsWyQtd4LS0Ne4iewyn55qYWKxRV5SSFgOGdkcfPYkCwURKxnIzQrIqYEyChoaSXExrzWpw1NDqvc5/wDVBBM5RLINj01yt30EQ5gs1LB8RUR+fWXoUKy1bVgHPG+U/7YuAkJ+QHIHGlhwqVNAmp1jaqD0c9tqzsZKdQ=
notifications:
  email: false
