language: go
sudo: required

go:
  - 1.6
env:
  matrix:
    # - TMP_GOOS=linux TMP_GOARCH=386
    - TMP_GOOS=linux TMP_GOARCH=amd64
    # - TMP_GOOS=windows TMP_GOARCH=amd64
    # - TMP_GOOS=windows TMP_GOARCH=386
    # - TMP_GOOS=darwin TMP_GOARCH=amd64
    # - TMP_GOOS=darwin TMP_GOARCH=386
  global:
    #  GITHUB_TOKEN
    - secure: "omw0SJff3lD9tIM1LSeWoDotXVyMbF2mNi6ZoIQa+dMSvHY+aQ7C9vLcCz9xaBHcwhwfIO4Fely7+vPw+rBpcYQyGPp1PxDLBsHuEHLN1QR5hzAZ84aVQTg8rWhTEikvdonBWJw8388g+ZPUIhlUy31QCNQXBEWCl3G2yljsfaxde2Ju0gZx+gcmtSyQZeNTGGap7GZwZ+MLfseZp45TlR9OgyqjMLNFXVdM8bQ7g6DHCVgQduxDCachF0wmZ38O8T5M3qZf+5I0Zq39tuVyT6R3FHsyrDcK4GqLNqabTU0u9QwN77P/JUGEtgw4sZIaSBfQ35E4vVT3RhA85eaSLhf8AOdwAv9svWk+xsYlDlLj800Lk4YCaBYOmnAurwLS4i1csyoaAlnLzE4BDfNVkb2GMUekroK+hxVgsVMI8Gjz3RkkPxWhuN977eT8LL4gFqjRKxwEBC8zVTZYgGm4utLJOwYtXFq9zjeZndOtH+MUPGCeWxdHytMAGiJA1Jm3UJPYS6vdJnGZy2z4lKB2UTZBzFRaXqZv2HZ4ejvYJFVG1eMdp+S+r+gh6HWb4zTNz5tyalMUFXYLgARX116SFV6KClIXXX0E02B4h7/5bQpxE9d2Ts68rhrDukCrr5pqPQwLciQKmcN+vT/ALuoWdWQVH5B6zyqCQk5LVcCD8so="
    - VERSION=1.0.$TRAVIS_BUILD_NUMBER
    - PRODUCT_VERSION=v${VERSION}
    - OWNER=palette-software
    - PACKAGE=insight-tester
    # GP_PALETTE_PASSWORD
    - secure: "LdWnOffjxBKJoF5kEJz/HDj9hKCGJxrG5PyfA0XFNOOJtrshT842C1e+4AT+fDf8KFzZvNcQJi+mo11z1Pk1IhJI3w/j9vRhaub8Ts34Z1w9Ds+pr+wShUdh+A3krFQdfWncFmapD097Ztmp+6/vYji4k2ljczFqVfLDHp/4PC1uDGcKf0ubfRrRy1fvNIk23YjtZzLqp3goFIVr19JTDdk8NOXvuU+Pu+Jjhw9waUnmyE2KzZN40NenVX5omwA+y9SqNhXUwHFu9y9R9eMyHj06puEZG6RLaKvR85LK5D03K4EqsQ6X3MsG2yeL5hGAj90G52bPoyG1h2bHlkCUHgLZwgJZs0RInuEJm15Ccpv1MKCboMTYzjB6donCyvzItOgRumTrKreP6J4uBKdtx9qPHkxxcKCho1A39f4yFFOy+rH5D9Ji7R7OOZcUA8svCy/CgC3fULFiEclY0Qz4E7Vah2yenT3hppKLmJJslD4wsh0lpVdmrzbF8u/Gqp8SOSV1orw1mgV1MyhP12acDFrfJD4e2GsaXDEudcnjPK5s3eumoLoeRedRL0YYXObKXPsu5qcHA8BDJXA7unVGREZqiF41t93llP+pQhQDKqpa4mKIPGXJLOgWAGVNjfkdJ5z9hazml9vGjw5Rpisr6j4gtEVJkyHUOe3jYtOTmr4="
    - DEPLOY_HOST=rpm.palette-software.com
    - DEPLOY_PATH=/var/palette-rpm-repo
    - DEPLOY_USER=palette-rpm
    # DEPLOY_PASSWORD
    - secure: "DUHzEd/h/RUuXn0AlAkY6Iw3EUjS8DcLfMcgECAtny2ITLQm1Zv7szGXjjeqNPp38wcF6cNVXf4GuqpiCD9BIA9u6o+GU3qs+pFe/+pRY6C5dSLLF1keT1Mz8ChNdUI9huZQjRt11CETA4jDLGC4SgxAFdehjlY+Zc86GjUbY9r+8PkjWpdlzU9crGtpBTG0dSlcPdYByiumWKRAgG9pmneFkg9I1c1SZZWlZ9Uttl/FbuVpkgyRXEOiYqQrs6HWCA5Z/W2fAJqc8wHajSbQUVTAIXiiEXo8AyKjUrz6npV9w7A/+YRffTuDsfeGontMsNAZxb1twxA3bf6FMYjv0nke56PZQld8cGM97OkJnfvparbLTgy+fCxZIe24FNrxdZTIGDkUhByKdRopnCOVgthQBtxCqvdCqh4111axwuHUncXCoTfbXAY3CbD47B29F/QZcxglxKBkSBme6IZ08aqJhkEquJ3v4+aaGb946n2+KcyFMHlu/H2TXhg69Efqq22w9UKSxjhZWoUp28LP/FOLcXp4nqx1YIVTMa3gIM0xZj2MVp365BjLXsrbCUdDEWFgUWJ5XRrysisKnQM9LoSTN28c7tmrGAyygx87BJg0Jdgw3Rye3fzYJR8Pz5T1mjD7IfTgAqzFfj0TEA/28pg2ui32qzpcr6gd0WXrmm8="

# install the RPM package
addons:
  apt:
    packages:
      - rpm
      # To deploy the rpms, we need to ssh into places, and we dont want to store keys for now
      - sshpass

before_install:
  - export GOOS=${TMP_GOOS}
  - export GOARCH=${TMP_GOARCH}
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc

script:
  - go install -v ./...
  - chmod ugo+x travis_run_go_test.sh
  - ./travis_run_go_test.sh

after_success:
  - cd $GOPATH/bin/
  - export PCKG_DIR=`pwd`
  - export CURRENT_ENV_DIR=${GOOS}_${GOARCH}
  - export PCKG_FILE=${CURRENT_ENV_DIR}.zip
  - mkdir -p $CURRENT_ENV_DIR/sanity_check
  - cp -f $GOPATH/bin/* $CURRENT_ENV_DIR/
  - mv $CURRENT_ENV_DIR/dbcheck $CURRENT_ENV_DIR/sanity_check/
  - mv $CURRENT_ENV_DIR/csv_forker $CURRENT_ENV_DIR/sanity_check/
  # Make sure that out sanity checks are also bundled with the executable
  - cp -R $TRAVIS_BUILD_DIR/dbcheck/tests $CURRENT_ENV_DIR/sanity_check/
  - zip -r $PCKG_FILE $CURRENT_ENV_DIR

  # build the rpm
  - cd ${TRAVIS_BUILD_DIR}/dbcheck
  - if [ "${CURRENT_ENV_DIR}" == "linux_amd64" ]; then rpmbuild -bb --buildroot $(pwd) --define "version $VERSION" --define "buildrelease 1" --define 'source_dir $TRAVIS_BUILD_DIR' --define "_rpmdir $(pwd)/_build" palette-insight-sanity-check.spec; fi

before_deploy:
  # It can cause the deploy to fail, if you are not in the build dir at deploy time.
  - cd $TRAVIS_BUILD_DIR

deploy:
  skip_cleanup: true
  provider: script
  # Only deploy from the master branch (and if we don't have a tag specified, because they are auto-committed)
  script: $TRAVIS_BUILD_DIR/release-to-github.sh
  on:
    branch: master
    tags: false

notifications:
  email: false
