DbConnector:
    Host: dev-insight.palette-software.net
    Port: 5432
    User: palette_etl_user
    Password: palette123
    Database: palette
    Schema: go_test

# SplunkServerAddress: "SERVER_ADDRESS"
# SplunkToken: "TOKEN"
