DbConnector:
    Host: 127.0.0.1
    Port: 5432
    User: palette_etl_user
    Password: {{ gp_palette_password }}
    Database: palette
    Schema: go_test

SplunkServerAddress: "diagnostics.palette-software.com"
SplunkToken: "F59DC3B4-AAB9-4330-ACED-682E1681B507"
SplunkCustomer: {{ splunk_host }}
