Databases:
    Hosts:
        - staging-insight.palette-software.net
        - isi-insight.palette-software.net
        - isi-qa-insight.palette-software.net
    Params:
        Port: 5432
        User: palette_etl_user
        Database: palette
        Password: palette123
SplunkServerAddress: "splunk-insight.palette-software.net"
# SplunkToken: "TOKEN"

